### ISSUE TITLE
Getting InputStream from a running container?

### ISSUE THREAD

**Issue by getvictor** [kpelykh/docker-java#1]
Is it possible to get the InputStream for stdout and stderr from a running container using docker-java, like you can from java.lang.Process?

Currently I'm trying to run a docker container without using this API by using ProcessBuilder.start(). However, I see that Process.waitFor() gets stuck and never returns for simple commands like "docker run base echo hello"

**Comment by kpelykh** [comment]
@getvictor
Both docker and docker-java are just REST clients to talk to docker daemon over http. When REST call is completed http connection is closed, so both stdout and stder is just a representation of what http call returns. In some cases, however HTTP call returns a stream of data,  eg. http://docs.docker.io/en/latest/api/docker_remote_api_v1.3/#attach-to-a-container. docker-java allows you to grab this output, like this:

```
ClientResponse response = dockerClient.logContainer(container.id);

StringWriter logwriter = new StringWriter();

try {
    LineIterator itr = IOUtils.lineIterator(response.getEntityInputStream(), "UTF-8");
    while (itr.hasNext()) {
        String line = itr.next();
        logwriter.write(line + (itr.hasNext() ? "\n" : ""));
        LOG.info(line);
     }
} finally {
       IOUtils.closeQuietly(response.getEntityInputStream());
}
```

But after you retrieved output stream, http connection will be closed.

Why do you need InputStream for stdout and stderr from a running container? Are you trying to implement web-based terminal for docker?

**Comment by getvictor** [comment]
@kpelykh 
I'll try your suggestion. I'm trying to execute some user-provided code inside a docker container, similar to what http://ideone.com/ does.

**Comment by kpelykh** [comment]
@getvictor you can try to upload user's bash script to container and then run it from inside of container. 

Here's how ansible doest it:

<127.0.0.1> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1373671266.66-55801780472244 && chmod a+rx $HOME/.ansible/tmp/ansible-1373671266.66-55801780472244 && echo $HOME/.ansible/tmp/ansible-1373671266.66-55801780472244'
<127.0.0.1> EXEC /bin/sh -c '/bin/bash /root/.ansible/tmp/ansible-1373671266.66-55801780472244/ping; rm -rf /root/.ansible/tmp/ansible-1373671266.66-55801780472244/ >/dev/null 2>&1'

**Comment by getvictor** [comment]
Yes, I'm already running a bash script from inside of container. I also want to see the stdout/stderr in real-time. The pattern I want to use is the following:
1. Start the container.
2. Collect the stdout/stderr results in a separate thread.
3. Wait for container.

I played around with your API, and I got it to work with some minor changes.

First, the connection manager should be pooling/multi-threaded. I think this is needed anyway to make your API multi-threaded and prevent the following exception:
`java.lang.IllegalStateException: Invalid use of SingleClientConnManager: connection still allocated.`

I used HttpClient 4.2 with this code.

``` java
SchemeRegistry schemeRegistry = new SchemeRegistry();
schemeRegistry.register(new Scheme("http", 4243, PlainSocketFactory.getSocketFactory()));

PoolingClientConnectionManager cm = new PoolingClientConnectionManager(schemeRegistry);
// Increase max total connection
cm.setMaxTotal(1000);
// Increase default max connection per route
cm.setDefaultMaxPerRoute(1000);

HttpClient httpClient = new DefaultHttpClient(cm);
client = new ApacheHttpClient4(new ApacheHttpClient4Handler(httpClient, null, false), clientConfig);
```

Second, I added `params.add("stream", "1");` in DockerClient.logContainer

**Comment by kpelykh** [comment]
Integrated your changes
