### ISSUE TITLE
Support to copy files or folders from a container

### ISSUE THREAD

**Issue by getvictor** [kpelykh/docker-java#10]
Can the API be upgraded to copy files or folders from a container?
http://docs.docker.io/en/latest/api/docker_remote_api_v1.5/#copy-files-or-folders-from-a-container

I'm trying to get it working in my local workarea with API v1.4, but so far Docker doesn't recognize my requests.

Otherwise, simply changing v1.3 to v1.4 in DockerClient doesn't cause any issues for me. Changing to v1.5, on the other hand, breaks the code.

**Comment by kpelykh** [comment]
I'll look at what needs to be done to DockerClient to support new  v1.5

**Comment by getvictor** [comment]
I got copy to work with v1.3, but I had comment out the following line in JsonClientFilter:

```
contentParams.put("charset", "UTF-8");
```
