### ISSUE TITLE
Using volumes with docker-java

### ISSUE THREAD

**Issue by michaeldejong** [kpelykh/docker-java#11]
I'm trying to set up a volume in my container which points to a folder on my host machine using docker-java. 

On the commandline I can do this with `docker run -v /home/michael:/workspace:ro <container-id> <command> <arguments>` for instance. But I don't seem to be able to do this with docker-java as well.

When I define my volume in ContainerConfig like so: `containerConfig.setVolumes("/home/michael:/workspace:ro");` I get a 500 error code back from the jersey client when running this. 

Do I need to define volumes differently? I noticed that the `setVolumes()` method takes an `Object` and not the expected `String` or `String[]`.

**Comment by dkatona** [comment]
Hi, if you still need to bind volumes with docker-java, I managed to do it this way:

``` java
ContainerConfig containerConfig = new ContainerConfig();
Map<String,Object> volumesMap = new HashMap<String, Object>();
volumesMap.put("/opt",new HashMap<String, String>());
containerConfig.setVolumes(volumesMap);
..
ContainerCreateResponse container = dockerClient.createContainer(containerConfig);
HostConfig hc = new HostConfig(new String[]{"/opt:/opt:rw"});

dockerClient.startContainer(container.getId(), hc);
```

It is not very well documented even in docker REST API reference, but the trick is that you need to first pass volumes in the format described here - https://github.com/dotcloud/docker/issues/1580, with jackson serialization, it can be achieved with above code.

**Comment by marcuslinke** [comment]
Closed as project moved to https://github.com/docker-java/docker-java. Please check if that issue still persist and reissue there if necessary.
