### ISSUE TITLE
Please qualify the API with a more recent Docker version

### ISSUE THREAD

**Issue by getvictor** [kpelykh/docker-java#12]
I tried using the API with a recent Docker 0.6.7, and I got intermittent timeouts when waiting for container, and intermittent "Socket closed" errors when reading from InputStream.

Some tweaks may be needed for recent Docker versions.

**Comment by kittylyst** [comment]
@kpelykh Could you email me (ben@jclarity.com)? I may be able to help here, but I would like to discuss with you first.

**Comment by kpelykh** [comment]
updated docker-java to Docker Client API v1.8, Docker Server version 0.7.6
