### ISSUE TITLE
UnrecognizedPropertyException running against server 0.8.1

### ISSUE THREAD

**Issue by dikonikon** [kpelykh/docker-java#25]
When running the test suite against docker server version 0.8.1 by invoking 'mvn clean install' I get a number of failed tests all with jackson UnrecognizedPropertyExceptions as below.

Is this an incompatibility with this server version?

Failed tests: 
  commitImage(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  restartContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testDockerBuilderAddFile(com.kpelykh.docker.client.test.DockerClientTest): 
  testDockerBuilderAddFolder(com.kpelykh.docker.client.test.DockerClientTest): 
  testDockerInfo(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "ExecutionDriver" (Class com.kpelykh.docker.client.model.Info), not marked as ignorable
  testImages(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "ExecutionDriver" (Class com.kpelykh.docker.client.model.Info), not marked as ignorable
  testKillContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testNetCatDockerfileBuilder(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testNginxDockerfileBuilder(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testPullImage(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "ExecutionDriver" (Class com.kpelykh.docker.client.model.Info), not marked as ignorable
  testRemoveImage(com.kpelykh.docker.client.test.DockerClientTest): Server error
  testStartContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testStopContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable
  testWaitContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "OnBuild" (Class com.kpelykh.docker.client.model.ContainerConfig), not marked as ignorable

Tests run: 22, Failures: 14, Errors: 0, Skipped: 0

Output from sudo docker version:

Client version: 0.8.1
Go version (client): go1.2
Git commit (client): a1598d1
Server version: 0.8.1
Git commit (server): a1598d1
Go version (server): go1.2
Last stable version: 0.8.1

**Comment by kpelykh** [comment]
Most likely Docker API slightly changed in 0.8. currently docker-java only supports 0.7.6 and older. 
It looks like OnBuild needs to be marked as Ignorable.

**Comment by dikonikon** [comment]
That's what I thought - I'll probably want to use this client so I'll see if I can fix it

**Comment by kpelykh** [comment]
If you fix it , please file a pull request and I'll merge it into mainstream branch. Thanks!

**Comment by dikonikon** [comment]
will do

**Comment by joeltucci** [comment]
I created a pull request adding in the new fields: https://github.com/kpelykh/docker-java/pull/26

**Comment by kpelykh** [comment]
merged into mainstream
