### ISSUE TITLE
Support for attach including stdin and stdout/stderr decoding

### ISSUE THREAD

**Issue by karchie** [kpelykh/docker-java#29]
Should be possible to use full range of functionality in POST /containers/{id}/attach. Right now can only do logs=1&stdin=false&stdout=true&stderr=true , and the response entity contains the raw (multiplexed) application/vnd.docker.raw-stream

**Comment by karchie** [comment]
I actually have a nearly-complete implementation for this, but would like some guidance on API. So far I have a new method for DockerClient:

public AttachedContainer attachContainer(final String containerId, final byte[] stdin,
            final OutputStream stdout, final OutputStream stderr,
            final boolean logs, final boolean stream)
The particular choice of types for stdin, stdout, stderr was mostly for convenience of implementation, I'm open to being convinced there's a better way. The stdin is streamed to the container, and stdout/stderr are demultiplexed and written to the provided streams (if non-null).

The returned AttachedContainer interface is a not-quite-Runnable:

public interface AttachedContainer extends Closeable {
    void run() throws DockerException;
}

not actually a Runnable because I want to be able to throw DockerExceptions, and not just run in the attachContainer method because run() waits for container completion and I wanted to leave the option of spinning that off in its own Thread. Arguably the AttachedContainer could instead be a start() and a waitFor(), or maybe the start() could be implicit in the constructor.

I can push to a branch in my forked repo if you'd like to see the details. I'd like to get this cleaned up before doing a PR.

**Comment by karchie** [comment]
arguably the logContainer methods should be switched to use this, but right now they return a jersey ClientResponse with the multiplexed stdout+stderr stream, and I don't think I can (or, probably, want to) reproduce that functionality.

**Comment by karchie** [comment]
here's the described first-pass implementation, tested lightly and only manually: https://github.com/karchie/docker-java/tree/attach-stream

**Comment by kpelykh** [comment]
@karchie thanks for your help! I'll review your changes and merge it into mainstream.

**Comment by getvictor** [comment]
I'm using a custom InputStream to handle the attach stream.
This way it can simply be used as a wrapper, and it does not need its own thread.
https://gist.github.com/getvictor/9997403

However, this version does not split the stream into stdout/stderr.

**Comment by karchie** [comment]
I've rewritten to clean up the interface a bit and to merge upstream changes, and have moved to this branch: https://github.com/karchie/docker-java/tree/attach-streams
But I like what @getvictor did and will think about how to invert the organization that way. I do need for my use case to read both stdout and stderr so that complicates things somewhat.

**Comment by marcuslinke** [comment]
Closed as project moved to https://github.com/docker-java/docker-java. Please check if that issue still persist and reissue there if necessary.
