### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by alexec** [kpelykh/docker-java#38]
Hi, I'm just starting out on a Maven plugin and was hoping to use your excellent library as the engine for it. I'd like to tame the logging, I'd hoped that by redirecting JCL via SLF4J to Logback, I could log via the Maven logger, but I'm getting HTTP written to the console, e.g.:

```
INFO: 1 * Client out-bound request
1 > GET http://127.0.0.1:4243/v1.8/version
1 > Accept: application/json
```

Do you have any thoughts?

**Comment by etux** [comment]
Please take a look at https://github.com/etux/docker-maven-plugin
