### ISSUE TITLE
Problems with docker 0.9.1

### ISSUE THREAD

**Issue by rferreira** [kpelykh/docker-java#40]
It seems that docker-java just cannot find any images with docker 0.9.1, no matter what i try I keep getting this error: 

com.kpelykh.docker.client.NotFoundException: 870f64002218e3a454b1492d1222bdaf6fe67b3fba624e5afae009b8e521f8f1 is an unrecognized image. Please pull the image first.
    at com.kpelykh.docker.client.DockerClient.createContainer(DockerClient.java:370)
    at com.kpelykh.docker.client.DockerClient.createContainer(DockerClient.java:352)
    at com.r.s.minion.services.ContainerService.run(ContainerService.java:178)
    at com.r.s.minion.cli.RunCommand.run(RunCommand.java:38)
    at com.r.s.minion.cli.RunCommand.run(RunCommand.java:17)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:72)
    at com.r.s.minion.Minion.main(Minion.java:27)
INFO  [2014-04-07 13:26:07,544] com.sun.jersey.api.client.filter.LoggingFilter: 1 \* Client out-bound request

docker info: 
$ docker version
Client version: 0.9.0
Go version (client): go1.2.1
Git commit (client): 2b3fdf2
Server version: 0.9.1
Git commit (server): 3600720
Go version (server): go1.2.1
Last stable version: 0.9.1, please update docker

**Comment by getvictor** [comment]
This may or may not be relevant. Don't use the _getVizImages_ method.

As of version 1.7 of the API:
**GET /images/viz**
    This URI no longer exists. The images -viz output is now generated in the client, using the /images/json data.

**Comment by rferreira** [comment]
Hey thanks for the quick response but unfortunately, these are just standard images (and it totally doesn't matter which image either). Here's the relevant code snippet: 

```
        DockerClient dc = new DockerClient("http://master:4243");

        ContainerConfig cc = new ContainerConfig();
        cc.setImage(imageID);
        cc.setHostName("NR-JOB-" + imageID);
        ContainerCreateResponse res = dc.createContainer(cc);
```

and the jersey logs: 

```
INFO  [2014-04-07 13:37:58,696] com.sun.jersey.api.client.filter.LoggingFilter: 1 * Client out-bound request
1 > POST http://master:4243/v1.8/containers/create
1 > Accept: application/json
1 > Content-Type: application/json
{"hostName":"NR-JOB-1ea4e9679","portSpecs":null,"user":"","tty":false,"stdinOpen":false,"stdInOnce":false,"memoryLimit":0,"memorySwap":0,"cpuShares":0,"attachStdin":false,"attachStdout":false,"attachStderr":false,"env":null,"cmd":null,"dns":null,"image":null,"volumes":null,"volumesFrom":"","entrypoint":[],"networkDisabled":false,"privileged":false,"workingDir":"","domainName":"","exposedPorts":null,"onBuild":null}

INFO  [2014-04-07 13:37:58,709] com.sun.jersey.api.client.filter.LoggingFilter: 1 * Client in-bound response
1 < 404
1 < Content-Type: application/json; charset=utf-8
1 < Date: Mon, 07 Apr 2014 13:38:01 GMT
1 < Content-Length: 30
1 < 
No such image:  (tag: latest)
```

**Comment by marcuslinke** [comment]
@rferreira This issue still persists?
