### ISSUE TITLE
No support for "push" command

### ISSUE THREAD

**Issue by sfitts** [kpelykh/docker-java#41]
The REST API provides support for image/push, but the API currently does not.  Seems pretty easy to add so I plan to do so.

**Comment by bmuschko** [comment]
@sfitts Did you get around to work on this yet?

**Comment by sfitts** [comment]
@bmuschko Unfortunately I got ambushed by my day job, so haven't had the time yet.

**Comment by alexec** [comment]
You can try my fork if you like… https://github.com/alexec/docker-java/blob/master/src/test/java/com/kpelykh/docker/client/test/DockerPushTest.java

**Comment by bmuschko** [comment]
@alexec Thanks for the pointer. Are you planning to contribute back to this repo or do you publish your own version of the artifact? This project hasn't been active for over 2 months.

@kpelykh Are you planning to merge some of the pull request anytime soon?

**Comment by kpelykh** [comment]
@bmuschko Yes, I will merge soon. I've been too swamped with my job lately and couldn't support this project. I'll try to find some time soon to go though pull-requests and open issues.

**Comment by bmuschko** [comment]
@kpelykh Awesome. Thanks for the feedback.

**Comment by alexec** [comment]
@bmuschko I'm hoping for a master merge, but my fork, while it works, is now a bit of a mess of whitespace changes and might not merge so well. I'd certainly like the push support to be cherry picked to @kpelykh original code. I've some thoughts about better forward/backwards compatibility too, as a lot of pulls are "please add support for v0.x"

**Comment by marcuslinke** [comment]
@kpelykh: Maybe you need support regarding project maintainance? I'm willing to help and i'm sure others are too. As docker itself moves forward so fast it would be great. WDYT?

**Comment by kpelykh** [comment]
@marcuslinke help would be great! Unfortunately I'm extremely busy with my current project, which doesn't involve docker, so I have almost no opportunity to dedicate any time to support docker-java. If somebody wants to help with merges, new features, I'd be happy to share this project with them.

**Comment by marcuslinke** [comment]
@kpelykh: Great! So if you would give me the appropriate permissions i will  merge some of the open pull requests. Additionally I think it  would be useful to start a 'docker-java-dev' google group  for discussions related to project development.

**Comment by kpelykh** [comment]
@marcuslinke Added you as a collaborator to the project

**Comment by marcuslinke** [comment]
@kpelykh: Thanks! Here is the google group: https://groups.google.com/forum/?hl=de#!forum/docker-java-dev

**Comment by marcuslinke** [comment]
Closed as @alexec changes are merged now.
