### ISSUE TITLE
Unit tests failing (setBinds)

### ISSUE THREAD

**Issue by EronWright** [kpelykh/docker-java#42]
Executing unit tests:
`mvn install -DskipTest=false`

Output (truncated):

```
Failed tests:
  restartContainer(com.kpelykh.docker.client.test.DockerClientTest): org.codehaus.jackson.map.JsonMappingException: Conflicting setter definitions for property "Binds": com.kpelykh.docker.client.model.HostConfig#setBinds(1 params) vs com.kpelykh.docker.client.model.HostConfig#setBinds(1 params)
```

The issue is likely due to e796c763f687b3140c175ac8e60d8f24e21bea79 since it introduced an overloaded setBinds method.

**Comment by alexec** [comment]
Fixed here: https://github.com/alexec/docker-java/

**Comment by marcuslinke** [comment]
Closed as @alexec changes are merged now.
