### ISSUE TITLE
Update to Jersey 2.x???

### ISSUE THREAD

**Issue by luismclglass** [kpelykh/docker-java#45]
Hi!

I have problem using the this library on my Jersey 2.x Project. The codehaus annotation aren't processed by my default JSON mapper.

Can I migrate to Jerser 2.x? or could I do some hack to fix it on my project. 

Thanks!

**Comment by marcuslinke** [comment]
Closed as project moved to https://github.com/docker-java/docker-java. Please check if that issue still persist and reissue there if necessary.
