### ISSUE TITLE
Update API to Work with Latest Docker Version

### ISSUE THREAD

**Issue by saden1** [kpelykh/docker-java#50]
docker-java client doesn't seem with the latest docker version:

``` bash
Client version: 0.11.0
Client API version: 1.11
Go version (client): go1.2.1
Git commit (client): 15209c3
Server version: 0.11.0
Server API version: 1.11
Git commit (server): 15209c3
Go version (server): go1.2.1
Last stable version: 0.11.0
```

I am running into the following issue:

```
com.sun.jersey.api.client.ClientHandlerException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "ExecDriver" (Class com.kpelykh.docker.client.model.ContainerInspectResponse), not marked as ignorable
 at [Source: com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream@5328a9c1; line: 1, column: 1331] (through reference chain: com.kpelykh.docker.client.model.ContainerInspectResponse["ExecDriver"])
```

Perhaps docker-java deserialization should be more lenient when it comes to unrecognized properties?

**Comment by EronWright** [comment]
Agreed, Docker uses an open schema (i.e. new elements are safe to add without bumping the protocol version, and are returned for downlevel versions) - see [issue 4787](https://github.com/dotcloud/docker/issues/4787).

The solution is to add an annotation to all model classes:

```
@JsonIgnoreProperties(ignoreUnknown = true)
```

**Comment by marcuslinke** [comment]
Should be fixed with the latest commits. All model classes are annotated with 

```
@JsonIgnoreProperties(ignoreUnknown = true)
```

Thanks @EronWright !

**Comment by defender** [comment]
Hi when and where latest version can be downloaded
