### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by alexec** [kpelykh/docker-java#57]
Hi @marcuslinke, I noted that there are now some ways to configure. Do we want to make them common some how? 
- URL
- API Version (I had to updated boot2docker today)
- Username
- Password 
- Email

Some thoughts, perhaps we might want to search for them in common places:
1. Programmatic. 
2. System properties
3. `docker.io.properties` file is the class path. Or maybe `docker-java.properties`.
4. `~/.docker.io.propreties` in the file system.

Thoughts?

**Comment by alexec** [comment]
E.g Voila:

https://github.com/alexec/docker-java/compare/config-spike?expand=1

Thoughts?

**Comment by marcuslinke** [comment]
Hi @alexec: Good idea! Your code looks good to me, so would you file a pull request please? Thanks!
