### ISSUE TITLE
release plugin to 2.5

### ISSUE THREAD

**Issue by alexec** [kpelykh/docker-java#62]
@marcuslinke I found a problem with maven-release-plugin 2.3.1:

https://jira.codehaus.org/browse/MRELEASE-812

Might be good to update to 2.5?

**Comment by marcuslinke** [comment]
Thanks for the hint! I've updated to 2.5 meanwhile.

Closed as project moved to https://github.com/docker-java/docker-java. Please check if that issue still persist and reissue there if necessary.
