### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by bmuschko** [kpelykh/docker-java#64]
There have been all these great contributions lately. Could we please release a new version of the library to Maven Central? If you already have everything set up and permissions to publish to the group ID, this shouldn't take longer than 10 minutes.

**Comment by marcuslinke** [comment]
@bmuschko Currently i prepare a  release under a new groupId. This includes a move to https://github.com/docker-java/docker-java. Hopefully i will succeed within the next few days.

**Comment by marcuslinke** [comment]
Its done.

```
<dependency>
    <groupId>com.github.docker-java</groupId>
    <artifactId>docker-java</artifactId>
    <version>0.8.2</version>
</dependency>
```

Further development will be continue here: https://github.com/docker-java/docker-java. Next release will change package names as well.

**Comment by bmuschko** [comment]
Perfect! Thank you very much.
