### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ctrimble** [kpelykh/docker-java#7]
Would you be willing to publish to Maven Central using [Sonatype's OSS Maven Repository](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide)?  I am willing to provide the needed patch and assistance with the process.

**Comment by kpelykh** [comment]
Sure! I'll follow instructions on their website and will let you know if I have any questions regarding the process

**Comment by kpelykh** [comment]
@ctrimble Uploaded to Sonatype OSS. https://oss.sonatype.org/content/repositories/snapshots/com/kpelykh/docker-java

**Comment by ctrimble** [comment]
Thanks!

**Comment by ayush** [comment]
@kpelykh it looks like the docker-java snapshots at sonatype have not been updated for a while. Would it be possible for you to publish the latest 0.7.6-SNAPSHOT there?

**Comment by thiagolocatelli** [comment]
Whats the update of this issue? I want to start using docker-java on my project but the dependency is not available at the main repository.

**Comment by kpelykh** [comment]
@thiagolocatelli 
I updated snapshot in maven central to version 0.8.1
https://oss.sonatype.org/service/local/repositories/snapshots/content/com/kpelykh/docker-java/0.8.1-SNAPSHOT

**Comment by marcuslinke** [comment]
@kpelykh 
Why there aren't any releases somewhere?

**Comment by kpelykh** [comment]
The following artifact has been released to the maven central.
<dependency>
      <groupId>com.kpelykh</groupId>
      <artifactId>docker-java</artifactId>
      <version>0.8.1</version>
</dependency>

**Comment by marcuslinke** [comment]
@kpelykh thanks!
